### ISSUE TITLE
如果交易没进打包池，就卡住在这了。

### ISSUE THREAD

**Issue by zhanghan328** [goldenfiredo/rarity#3]
summoner id: 1183956
{"0":"0","1":"0","2":"6","3":"1","_xp":"0","_log":"0","_class":"6","_level":"1"}
9/10/2021 4:32:56 PM
adventure
your account: 0xb84C0b5C2B004836162bf23064DFBF35F8717645
nonce: 246
transaction sent, wait for response.
hash:0xd1bac7877823be2c50a3b70a7059499ea6cd08d89675f4512b25f07d13f0a36a

一直在这等待。能否设置个时间来重新执行

**Comment by goldenfiredo** [comment]
no solution for now
